import { Product } from "./type";

export const Products: Product[] = [
  {
    id: 1,
    title: "Classic Margherita Pizza",
    desc: "Fresh mozzarella, basil leaves, and homemade tomato sauce on a crispy thin crust.",
    price: 45,
    catagory: "pizza",
    image: "/pizza.png",
    options: [
      { title: "small", price: 45 },
      { title: "medium", price: 60 },
      { title: "large", price: 75 },
    ],
  },
  {
    id: 2,
    title: "Spicy Chicken Burger",
    desc: "Juicy grilled chicken patty topped with spicy mayo, lettuce, and pickles in a soft brioche bun.",
    price: 30,
    catagory: "burger",
    image: "/burger.png",
  },
  {
    id: 3,
    title: "Veggie Delight Sandwich",
    desc: "Loaded with fresh veggies, cheese, and a tangy dressing on multigrain bread.",
    price: 25,
    catagory: "pizza",
    image: "/sandwitch.png",
  },
  {
    id: 4,
    title: "Creamy Alfredo Pasta",
    desc: "Penne pasta tossed in rich, creamy Alfredo sauce with a hint of garlic and parmesan.",
    price: 40,
    catagory: "pasta",
    image: "/pasta.png",
  },
  {
    id: 5,
    title: "BBQ Chicken Wings",
    desc: "Tender chicken wings coated in smoky BBQ sauce, served with ranch dip.",
    price: 35,
    catagory: "pizza",
    image: "/chickenWing.png",
  },
  {
    id: 6,
    title: "Choco Lava Cake",
    desc: "Warm chocolate cake with a gooey molten chocolate center, served with vanilla ice cream.",
    price: 20,
    catagory: "pizza",
    image: "/cake.png",
  },
];
export const FeaturedProducts: Product[] = [
  {
    id: 1,
    title: "Classic Margherita Pizza",
    desc: "Fresh mozzarella, basil leaves, and homemade tomato sauce on a crispy thin crust.",
    price: 45,
    catagory: "pizza",
    image: "/pizza.png",
  },
  {
    id: 2,
    title: "Spicy Chicken Burger",
    desc: "Juicy grilled chicken patty topped with spicy mayo, lettuce, and pickles in a soft brioche bun.",
    price: 30,
    catagory: "burger",
    image: "/burger.png",
  },
  {
    id: 3,
    title: "Veggie Delight Sandwich",
    desc: "Loaded with fresh veggies, cheese, and a tangy dressing on multigrain bread.",
    price: 25,
    catagory: "pizza",
    image: "/sandwitch.png",
  },
  {
    id: 4,
    title: "Creamy Alfredo Pasta",
    desc: "Penne pasta tossed in rich, creamy Alfredo sauce with a hint of garlic and parmesan.",
    price: 40,
    catagory: "pasta",
    image: "/pasta.png",
  },
  {
    id: 5,
    title: "BBQ Chicken Wings",
    desc: "Tender chicken wings coated in smoky BBQ sauce, served with ranch dip.",
    price: 35,
    catagory: "pizza",
    image: "/chickenWing.png",
  },
  {
    id: 6,
    title: "Choco Lava Cake",
    desc: "Warm chocolate cake with a gooey molten chocolate center, served with vanilla ice cream.",
    price: 20,
    catagory: "pizza",
    image: "/cake.png",
  },
];
